version: '3'

services:
  php:
    container_name: php
    build:
      context: ./php8.1
      dockerfile: dockerfile
    volumes:
      - ./php8.1/php.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www/html
    ports:
      - 8080:80
    links:
      - mysql:mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootps
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userps
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: always
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: userps
    ports:
      - "8081:80"
    depends_on:
      - mysql